name: "base"

file:
  open_tag:
    enabled: true
  max_line_length:
    enabled: true
    error_limit: 120
    warning_limit: -1
    info_limit: -1
    tab_expand: 4
  indentation:
    enabled: false
    style: "tab"
    count: 1
  encoding:
    enabled: true
style:
  bitwise:
    enabled: true
  quotes:
    enabled: true
    style: "single"
