name: "base"

file:
  open_tag:
    enabled: true
  end_tag:
    enabled: true
    end_with: false
  max_line_length:
    enabled: true
    error_limit: 120
    warning_limit: -1
    info_limit: -1
    tab_expand: 4
  indentation:
    enabled: false
    style: "tab"
    count: 1
  encoding:
    enabled: true
    bom: true
  no_inline_html:
    enabled: true
style:
  bitwise:
    enabled: true
  quotes:
    enabled: true
    style: "single"
  fully_qualified_namespaces:
    enabled: false
  elseif:
    enabled: true
  strict_equality:
    enabled: true
  private_variable_naming:
    enabled: true
    pattern: '/\$([a-z_\x7f-\xff]+)([a-zA-Z0-9\x7f-\xff]+)?/'
  var_var:
    enabled: true
  lower_bools:
    enabled: true
  variable_naming:
    enabled: true
    pattern: '/\$([a-z_\x7f-\xff]+)([a-zA-Z0-9\x7f-\xff]+)?/'
comments:
  no_shell_comments:
    enabled: true
whitespace:
  no_trailing_whitespace:
    enabled: true
  whitespace_around_braces:
    enabled: true
syntax:
  check:
    enabled: true
