name: "base"

file:
  open_tag:
    enabled: true
  end_tag:
    enabled: false
  max_line_length:
    enabled: true
    error_limit: 120
    warning_limit: -1
    info_limit: -1
    tab_expand: 4
  indentation:
    enabled: false
    style: "tab"
    count: 1
  encoding:
    enabled: true
    bom: true
style:
  bitwise:
    enabled: true
  quotes:
    enabled: true
    style: "single"
  fully_qualified_namespaces:
    enabled: true
  elseif:
    enabled: true
  strict_equality:
    enabled: true
  private_variable_naming:
    enabled: true
  var_var:
    enabled: true
  lower_bools:
    enabled: true
comments:
  no_shell_comments:
    enabled: true
