<?php 

	namespace PHPCheckstyle;

	class PHPCheckstyle_File {
		/**
		 * The absolute file path.
		 * @var string
		 */
		private $file = '';

		/**
		 * The EOL character the file is using.
		 * @var string
		 */
		public $eolChar = '';

		/**
		 * The PHPCheckstyle object controlling this check.
		 * @var PHPCheckstyle
		 */
		public $phpcs = NULL;

		/**
		 * The tokenizer being used for this file.
		 * @var object
		 */
		public $tokenizer = NULL;

		/**
		 * The number of tokens in this file.
		 * @var integer
		 */
		public $numTokens = 0;

		/**
		 * Tokens stack map.
		 * @var array
		 */
		private $_tokens = array();

		/**
		 * Any errors raised by this file.
		 * @var array
		 */
		private $_errors = array();

		/**
		 * Warnings raised by this file
		 * @var array
		 */
		private $_warnings = array();
		
		/**
		 * Lines ignored by PHPCheckstyle.
		 * @var array
		 */
		private $_ignoredLines = array();

		/**
		 * Number of errors raised.
		 * @var integer
		 */
		private $_errorCount = 0;

		/**
		 * Number of warnings raised.
		 * @var integer
		 */
		private $_warningCount = 0;

		/**
		 * Array of checks listening to this file.
		 * @var array
		 */
		private $_listeners = array();

		/**
		 * The class name of the check currently processing the file.
		 * @var string
		 */
		private $_activeListener = '';
		
		/**
		 * Store how long each check took.
		 * @var array
		 */
		private $_listenerTimers = array();

		/**
		 * An array of extensions mapping to the tokenizer to use.
		 * @var array
		 */
		protected $tokenizers = array();

		/**
		 * An array of rules generated by .phpcheckstyle.yml
		 * @var array
		 */
		protected $check = array();	
	}